# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf_Scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='value',
            field=models.IntegerField(),
        ),
    ]
