# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uf_Scraping', '0002_auto_20171229_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 29, 2, 16, 53, 530201, tzinfo=utc)),
        ),
    ]
