# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uf_Scraping', '0003_auto_20171228_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 29, 2, 17, 20, 169303, tzinfo=utc)),
        ),
    ]
