# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uf_Scraping', '0004_auto_20171228_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 12, 29, 18, 39, 45, 274652, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='money',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
